name: Build Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  build:
    name: Build Pull Request
    if: ${{ github.repository == 'spring-projects/spring-webflow' }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Set Up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '17'
      - name: Check Out
        uses: actions/checkout@v5
      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
      - name: Build
        env:
          CI: 'true'
          GRADLE_ENTERPRISE_URL: 'https://ge.spring.io'
        run: ./gradlew -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false --no-daemon --no-parallel --continue build
      - name: Print JVM Thread Dumps When Cancelled
        if: cancelled()
        uses: ./.github/actions/print-jvm-thread-dumps
      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: build-reports
          path: '**/build/reports/'
